### ISSUE TITLE
Segfault at runtime

### ISSUE THREAD

**Issue by parkerlreed** [AlexandreRouma/SDRPlusPlus#69]
Arch Linux
gcc 10.2.0
rtl-sdr 1:0.8.0-1
soapysdr 0.7.2-3
soapyrtlsdr 0.3.0-2

Disabled all the backends except RTL-TCP and soapy in the cmake config. I don't have a dongle on me at the moment, so I'm not sure if missing that is causing the crash. Just wanted to check out the GUI.

```
[parker@stealth build]$ ./sdrpp 
[2021-02-12 16:42:38.152] [info] SDR++ v0.2.5_beta
[2021-02-12 16:42:38.152] [info] Loading config
Segmentation fault (core dumped)
```

```
#0  0x00007f88584fa59f in stbir__decode_scanline (stbir_info=stbir_info@entry=0x7fff96fc9380, n=n@entry=-3072) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:1281
        decode_pixel_index = -256
        input_pixel_index = <optimized out>
        channels = 4
        alpha_channel = <optimized out>
        type = <optimized out>
        colorspace = <optimized out>
        input_w = <optimized out>
        input_stride_bytes = <optimized out>
        decode_buffer = 0x7f883c1f5ff8
        edge_horizontal = STBIR_EDGE_CLAMP
        edge_vertical = <optimized out>
        in_buffer_row_offset = <optimized out>
        input_data = 0x0
        decode = <optimized out>
        max_x = 576
        x = -64
        c = 0
#1  0x00007f88584f220b in stbir__decode_and_resample_downsample (stbir_info=0x7fff96fc9380, n=-3072) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:1672
No locals.
#2  stbir__buffer_loop_downsample (stbir_info=0x7fff96fc9380) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2187
        out_last_scanline = 0
        out_first_scanline = -3
        out_center_of_in = <optimized out>
        scale_ratio = 0.000488296151
        output_h = 16
        max_y = 36863
        pixel_margin = <optimized out>
        in_pixels_radius = 4095.875
        y = -3072
        out_last_scanline = <optimized out>
        out_first_scanline = <optimized out>
        out_center_of_in = <optimized out>
#3  stbir__resize_allocated (info=0x7fff96fc9380, input_data=<optimized out>, input_stride_in_bytes=<optimized out>, output_data=<optimized out>, output_stride_in_bytes=<optimized out>, alpha_channel=<optimized out>, 
    flags=<optimized out>, type=<optimized out>, edge_horizontal=<optimized out>, edge_vertical=<optimized out>, colorspace=<optimized out>, tempmem=0x7f883c102010, tempmem_size_in_bytes=1056967936)
    at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2410
        memory_required = <optimized out>
        width_stride_input = <optimized out>
        width_stride_output = <optimized out>
#4  stbir__resize_arbitrary (alloc_context=<optimized out>, input_data=<optimized out>, input_data@entry=0x0, input_w=<optimized out>, input_h=<optimized out>, input_stride_in_bytes=<optimized out>, output_data=<optimized out>, 
    output_data@entry=0x561369762540, output_w=output_w@entry=16, output_h=16, output_stride_in_bytes=64, s0=<optimized out>, t0=<optimized out>, s1=<optimized out>, t1=<optimized out>, transform=0x0, channels=4, alpha_channel=-1, 
    flags=0, type=STBIR_TYPE_UINT8, h_filter=STBIR_FILTER_DEFAULT, v_filter=STBIR_FILTER_DEFAULT, edge_horizontal=STBIR_EDGE_CLAMP, edge_vertical=STBIR_EDGE_CLAMP, colorspace=STBIR_COLORSPACE_LINEAR)
    at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2448
        info = {input_data = 0x0, input_w = 512, input_h = 32767, input_stride_bytes = 2048, output_data = 0x561369762540, output_w = 16, output_h = 16, output_stride_bytes = 64, s0 = 0, t0 = 0, s1 = 1, t1 = 1, horizontal_shift = 0, 
          vertical_shift = 0, horizontal_scale = 0.03125, vertical_scale = 0.000488296151, channels = 4, alpha_channel = -1, flags = 3, type = STBIR_TYPE_UINT8, horizontal_filter = STBIR_FILTER_MITCHELL, 
          vertical_filter = STBIR_FILTER_MITCHELL, edge_horizontal = STBIR_EDGE_CLAMP, edge_vertical = STBIR_EDGE_CLAMP, colorspace = STBIR_COLORSPACE_LINEAR, horizontal_contributors = 0x7f883c102010, 
          horizontal_coefficients = 0x7f883c103410, vertical_contributors = 0x7f883c105c10, vertical_coefficients = 0x7f883c155c08, decode_buffer_pixels = 640, decode_buffer = 0x7f883c1f5bf8, horizontal_buffer = 0x7f883c1f83f8, 
          horizontal_coefficient_width = 4, vertical_coefficient_width = 4, horizontal_filter_pixel_width = 128, vertical_filter_pixel_width = 8192, horizontal_filter_pixel_margin = 64, vertical_filter_pixel_margin = 4096, 
          horizontal_num_contributors = 640, vertical_num_contributors = 40959, ring_buffer_length_bytes = 256, ring_buffer_num_entries = 8193, ring_buffer_first_scanline = 11, ring_buffer_last_scanline = 0, ring_buffer_begin_index = -1, 
          ring_buffer = 0x7f883c1f84f8, encode_buffer = 0x0, horizontal_contributors_size = 5120, horizontal_coefficients_size = 10240, vertical_contributors_size = 327672, vertical_coefficients_size = 655344, decode_buffer_size = 10240, 
          horizontal_buffer_size = 256, ring_buffer_size = 2097408, encode_buffer_size = 0}
        memory_required = 1056967936
        extra_memory = <optimized out>
        result = <optimized out>
#5  0x00007f88584f6f6c in stbir_resize_uint8 (input_pixels=0x0, input_w=0, input_h=0, input_stride_in_bytes=-64, output_pixels=0x561369762540 "b\237@\b\026V", output_w=16, output_h=16, output_stride_in_bytes=64, num_channels=4)
    at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2463
No locals.
#6  sdrpp_main (argc=<optimized out>, argv=<optimized out>) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/core.cpp:228
        defConfig = {m_type = nlohmann::detail::value_t::null, m_value = {object = 0x0, array = 0x0, string = 0x0, binary = 0x0, boolean = false, number_integer = 0, number_unsigned = 0, number_float = 0}}
        resDir = ""
        bandColors = {m_type = nlohmann::detail::value_t::null, m_value = {object = 0x0, array = 0x0, string = 0x0, binary = 0x0, boolean = false, number_integer = 0, number_unsigned = 0, number_float = 0}}
        icons = {{width = -1761830528, height = 32767, pixels = 0x1 <error: Cannot access memory at address 0x1>}, {width = 48, height = 0, pixels = 0x0}, {width = -1761830496, height = 32767, pixels = 0x0}, {width = 1487974912, 
            height = 32648, pixels = 0x1 <error: Cannot access memory at address 0x1>}, {width = 1766324640, height = 22035, pixels = 0x26 <error: Cannot access memory at address 0x26>}, {width = 52, height = 0, pixels = 0x0}, {
            width = 512, height = 32767, pixels = 0x0}, {width = 16, height = 16, pixels = 0x561369762540 "b\237@\b\026V"}, {width = 24, height = 24, pixels = 0x56136975b810 "@\240NW\210\177"}, {width = 32, height = 32, 
            pixels = 0x561369806e10 "\200\240NW\210\177"}}
        glsl_version = <optimized out>
        winWidth = <optimized out>
        winHeight = <optimized out>
        monitor = <optimized out>
        window = 0x5613694bcae0
        io = <optimized out>
        _maximized = <optimized out>
        fsHeight = <optimized out>
        fsWidth = <optimized out>
        fsPosX = <optimized out>
        fsPosY = <optimized out>
#7  0x00007f885734fb25 in __libc_start_main () from /usr/lib/libc.so.6
No symbol table info available.
#8  0x0000561367a7b06e in _start ()
No symbol table info available.
cat: b: No such file or directory
[parker@stealth build]$ cat gdb.txt
#0  0x00007f88584fa59f in stbir__decode_scanline (stbir_info=stbir_info@entry=0x7fff96fc9380, n=n@entry=-3072) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:1281
        decode_pixel_index = -256
        input_pixel_index = <optimized out>
        channels = 4
        alpha_channel = <optimized out>
        type = <optimized out>
        colorspace = <optimized out>
        input_w = <optimized out>
        input_stride_bytes = <optimized out>
        decode_buffer = 0x7f883c1f5ff8
        edge_horizontal = STBIR_EDGE_CLAMP
        edge_vertical = <optimized out>
        in_buffer_row_offset = <optimized out>
        input_data = 0x0
        decode = <optimized out>
        max_x = 576
        x = -64
        c = 0
#1  0x00007f88584f220b in stbir__decode_and_resample_downsample (stbir_info=0x7fff96fc9380, n=-3072) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:1672
No locals.
#2  stbir__buffer_loop_downsample (stbir_info=0x7fff96fc9380) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2187
        out_last_scanline = 0
        out_first_scanline = -3
        out_center_of_in = <optimized out>
        scale_ratio = 0.000488296151
        output_h = 16
        max_y = 36863
        pixel_margin = <optimized out>
        in_pixels_radius = 4095.875
        y = -3072
        out_last_scanline = <optimized out>
        out_first_scanline = <optimized out>
        out_center_of_in = <optimized out>
#3  stbir__resize_allocated (info=0x7fff96fc9380, input_data=<optimized out>, input_stride_in_bytes=<optimized out>, output_data=<optimized out>, output_stride_in_bytes=<optimized out>, alpha_channel=<optimized out>, 
    flags=<optimized out>, type=<optimized out>, edge_horizontal=<optimized out>, edge_vertical=<optimized out>, colorspace=<optimized out>, tempmem=0x7f883c102010, tempmem_size_in_bytes=1056967936)
    at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2410
        memory_required = <optimized out>
        width_stride_input = <optimized out>
        width_stride_output = <optimized out>
#4  stbir__resize_arbitrary (alloc_context=<optimized out>, input_data=<optimized out>, input_data@entry=0x0, input_w=<optimized out>, input_h=<optimized out>, input_stride_in_bytes=<optimized out>, output_data=<optimized out>, 
    output_data@entry=0x561369762540, output_w=output_w@entry=16, output_h=16, output_stride_in_bytes=64, s0=<optimized out>, t0=<optimized out>, s1=<optimized out>, t1=<optimized out>, transform=0x0, channels=4, alpha_channel=-1, 
    flags=0, type=STBIR_TYPE_UINT8, h_filter=STBIR_FILTER_DEFAULT, v_filter=STBIR_FILTER_DEFAULT, edge_horizontal=STBIR_EDGE_CLAMP, edge_vertical=STBIR_EDGE_CLAMP, colorspace=STBIR_COLORSPACE_LINEAR)
    at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2448
        info = {input_data = 0x0, input_w = 512, input_h = 32767, input_stride_bytes = 2048, output_data = 0x561369762540, output_w = 16, output_h = 16, output_stride_bytes = 64, s0 = 0, t0 = 0, s1 = 1, t1 = 1, horizontal_shift = 0, 
          vertical_shift = 0, horizontal_scale = 0.03125, vertical_scale = 0.000488296151, channels = 4, alpha_channel = -1, flags = 3, type = STBIR_TYPE_UINT8, horizontal_filter = STBIR_FILTER_MITCHELL, 
          vertical_filter = STBIR_FILTER_MITCHELL, edge_horizontal = STBIR_EDGE_CLAMP, edge_vertical = STBIR_EDGE_CLAMP, colorspace = STBIR_COLORSPACE_LINEAR, horizontal_contributors = 0x7f883c102010, 
          horizontal_coefficients = 0x7f883c103410, vertical_contributors = 0x7f883c105c10, vertical_coefficients = 0x7f883c155c08, decode_buffer_pixels = 640, decode_buffer = 0x7f883c1f5bf8, horizontal_buffer = 0x7f883c1f83f8, 
          horizontal_coefficient_width = 4, vertical_coefficient_width = 4, horizontal_filter_pixel_width = 128, vertical_filter_pixel_width = 8192, horizontal_filter_pixel_margin = 64, vertical_filter_pixel_margin = 4096, 
          horizontal_num_contributors = 640, vertical_num_contributors = 40959, ring_buffer_length_bytes = 256, ring_buffer_num_entries = 8193, ring_buffer_first_scanline = 11, ring_buffer_last_scanline = 0, ring_buffer_begin_index = -1, 
          ring_buffer = 0x7f883c1f84f8, encode_buffer = 0x0, horizontal_contributors_size = 5120, horizontal_coefficients_size = 10240, vertical_contributors_size = 327672, vertical_coefficients_size = 655344, decode_buffer_size = 10240, 
          horizontal_buffer_size = 256, ring_buffer_size = 2097408, encode_buffer_size = 0}
        memory_required = 1056967936
        extra_memory = <optimized out>
        result = <optimized out>
#5  0x00007f88584f6f6c in stbir_resize_uint8 (input_pixels=0x0, input_w=0, input_h=0, input_stride_in_bytes=-64, output_pixels=0x561369762540 "b\237@\b\026V", output_w=16, output_h=16, output_stride_in_bytes=64, num_channels=4)
    at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/imgui/stb_image_resize.h:2463
No locals.
#6  sdrpp_main (argc=<optimized out>, argv=<optimized out>) at /home/parker/Downloads/FEX/build/SDRPlusPlus/core/src/core.cpp:228
        defConfig = {m_type = nlohmann::detail::value_t::null, m_value = {object = 0x0, array = 0x0, string = 0x0, binary = 0x0, boolean = false, number_integer = 0, number_unsigned = 0, number_float = 0}}
        resDir = ""
        bandColors = {m_type = nlohmann::detail::value_t::null, m_value = {object = 0x0, array = 0x0, string = 0x0, binary = 0x0, boolean = false, number_integer = 0, number_unsigned = 0, number_float = 0}}
        icons = {{width = -1761830528, height = 32767, pixels = 0x1 <error: Cannot access memory at address 0x1>}, {width = 48, height = 0, pixels = 0x0}, {width = -1761830496, height = 32767, pixels = 0x0}, {width = 1487974912, 
            height = 32648, pixels = 0x1 <error: Cannot access memory at address 0x1>}, {width = 1766324640, height = 22035, pixels = 0x26 <error: Cannot access memory at address 0x26>}, {width = 52, height = 0, pixels = 0x0}, {
            width = 512, height = 32767, pixels = 0x0}, {width = 16, height = 16, pixels = 0x561369762540 "b\237@\b\026V"}, {width = 24, height = 24, pixels = 0x56136975b810 "@\240NW\210\177"}, {width = 32, height = 32, 
            pixels = 0x561369806e10 "\200\240NW\210\177"}}
        glsl_version = <optimized out>
        winWidth = <optimized out>
        winHeight = <optimized out>
        monitor = <optimized out>
        window = 0x5613694bcae0
        io = <optimized out>
        _maximized = <optimized out>
        fsHeight = <optimized out>
        fsWidth = <optimized out>
        fsPosX = <optimized out>
        fsPosY = <optimized out>
#7  0x00007f885734fb25 in __libc_start_main () from /usr/lib/libc.so.6
No symbol table info available.
#8  0x0000561367a7b06e in _start ()
```

**Comment by parkerlreed** [comment]
As noted on Reddit, needs to be run from installation instead of build directory. Loads now. Thanks!
